export const enum keys {
  ALL_MARKETS = 'ALL_MARKETS',
  ALL_PRODUCTS = 'ALL_PRODUCTS',
  ALL_PRODUCERS = 'ALL_PRODUCERS',
  ALL_PRODUCER_PRODUCTS = 'ALL_PRODUCER_PRODUCTS',
  ALL_PAYMENTS = 'ALL_PAYMENTS'
}
