export const maxSize = {
  ADDRESS_STATE: 35,
  ADDRESS_CITY: 58,
  ADDRESS_COMPLEMENT: 30,
  ADDRESS_DISTRICT: 50,
  ADDRESS_STREET: 100,
  ADDRESS_ZIP_CODE: 9,
  PRODUCT_NAME: 100,
  PRODUCT_TYPE: 50,
  UNIT_MEASURE_ABBREVIATION: 10,
  UNIT_MEASURE_NAME: 50,
  USER_DOCUMENT: 14,
  USER_EMAIL: 100,
  USER_NAME: 150,
  USER_PASSWORD: 1028,
  USER_PHONE: 11
};
